local map = vim.keymap.set
vim.g.mapleader = " "
local opts = { silent = true }
map({ "n", "i" }, "<C-z>", "<Cmd>undo<CR>", opts)
map("n", "xx", '"_dd', { noremap = true, silent = true })
map("n", "<leader>hl", "<Cmd>nohlsearch<CR>", opts)
map("n", "<leader>bh", "<Cmd>BufferLineCyclePrev<CR>", opts)
map("n", "<leader>bl", "<Cmd>BufferLineCycleNext<CR>", opts)
map("n", "<leader>bp", "<Cmd>BufferLineCyclePick<CR>", opts)
map("n", "<leader>bd", "<Cmd>Bdelete<CR>", opts)
map("n", "<leader>hp", "<Cmd>HopWord<CR>", opts)
map("n", "<leader>lr", "<Cmd>Lspsaga rename<CR>", opts)
map("n", "<leader>lc", "<Cmd>Lspsaga code_action<CR>", opts)
map("n", "<leader>ld", "<Cmd>Lspsaga definition<CR>", opts)
map("n", "<leader>lh", "<Cmd>Lspsaga hover_doc<CR>", opts)
map("n", "<leader>lR", "<Cmd>Lspsaga finder<CR>", opts)
map("n", "<leader>ln", "<Cmd>Lspsaga diagnostic_jump_next<CR>", opts)
map("n", "<leader>lp", "<Cmd>Lspsaga diagnostic_jump_prev<CR>", opts)
map("n", "<leader>lf", function()
  vim.lsp.buf.format({ async = true })
end, opts)
